### PR TITLE
Make Igor cross-platform

### PR DESCRIPTION
**Pull request by flipsasser**
Hi Dave,

I've managed to get Igor to run correctly on a Mac desktop. Mostly it's the massaging of UIView \* into id and putting a few other pieces together on the auto-registration with Frank.

Anyway, I have it running in a local project and it actually. Freaking. Works!

So. I'm very excited. If you're interested in making Igor available to a whole bunch of other folk, I recommend you take a look at the changes in here! If not, no big deal; I'm happy to maintain this fork for a time.

Thanks for such an amazing piece of software! I love Igor.

Flip

### CODE REVIEW

**Comment by dhemery** [comment]
Awesome!  I'll take a closer look at this over the next few days.  You're doing some things I haven't had to learn about before (like making a framework), and I'll want to make sure I understand what's going on.

I would prefer to minimize the number of places in the code that know the difference between Cocoa and UIKit.  I might, for example, hide that knowledge in a small set of classes, one set for UIKit and another for Cocoa.  Then have a single #ifdef that selects the appropriate class(es) for use by the rest of the code.  But I won't hold up the pull request for that.

And you've given me another idea (that I don't have the knowledge to pull off... yet):  Make Igor independent of Frank, so that it could be used to create other UIKit/Cocoa GUI drivers.

**Comment by flipsasser** [comment]
Hi _Dale,_

I'm so sorry I called you "Dave!" That must happen all the time and be super-annoying.

Anyway! Regarding your comments:
1. The README is already out of date. It _now_ builds a static library for the x86_64 architecture. Just as an aside, I'm not 100% sure this is accurate, but I believe the big difference between that and a framework is the bundling of header files alongside the library. Grain of salt!
2. I'm 100% with you on the number of places in the code I used #ifdefs. My first approach was to set a static const to class types in one #ifdef, but guess what? Objective-C classes aren't available when setting a static variable, for whatever reason. So I wound up doing the interpolation in ViewFactory and replacing UIWhatever \* pointers with ids. It's not a great solution, but when you're traversing a view hierarchy, assuming it duck-types as an NSView or UIView seems reasonable. Still - I couldn't get away with it. I had to change a test because `accessibilityHint' is UIKit only, and then UIWindow and NSWindow don't behave the same, so I wound up littering the space. I'm happy to try and clean that up if you don't feel like it.
3. I could not agree MORE with an independent Igor! I'm a Ruby developer 50% of the time, but I hate writing integration tests for Objective-C in Ruby. My unit tests are written in Objective-C; why not my integration tests? I think it's reasonable to start with an "Rspec request spec" style approach - a Capybara-esque driver (that uses Igor for integration tests) inside of an Objective-C unit test structure. Maybe people would / could opt for Kiwi or OCHamcrest or whatever additional "expectation" library they felt they needed, but you'd have your tests and your app written in the same language and if you could make it a simple enough tool, every other Objective-C developer who _doesn't_ use Ruby (or want to learn it) could benefit from something like that.
4. Please don't ever learn from me! I know enough Objective-C to be dangerous but not enough to learn from. I'm still coming up.

Thanks for looking at my pull request! One last thing - my Xcode inserts two spaces to your four. I tried to re-indent in your style where I could, but I probably missed some spots. Sorry!

**Comment by dhemery** [comment]
Well, most people don't call me at all &lt;rimshot />, so _Dave_ is an improvement on that.

**Comment by flipsasser** [comment]
Boom!

**Comment by flipsasser** [comment]
Hey Dave, this PR is probably out-of-date at this point. Any interest in my revisiting this issue?

**Comment by flipsasser** [comment]
Prolly just gonna call this one `not_a_thing` at this point!

**Pull request closed without merging**
